[package]
name = "snarfit"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "^0"
clap = { version = "^4", features = ["derive", "cargo", "unicode"] }
thiserror = "^2"
log = "^0"
env_logger = "^0"
